---
run:
  timeout: 6m
  allow-parallel-runners: true

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: false

linter-settings:
  lll:
    line-length: 220
  gosec:
    includes:
      - G401
      - G306
      - G101
    excludes:
      - G204
    config:
      G306: "0600"
      G101:
        pattern: "(?i)example"
        ignore_entropy: false
        entropy_threshold: "80.0"
        per_char_threshold: "3.0"
        truncate: "32"

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - wrapcheck
    - testpackage
    - paralleltest
    - nestif
    - godot
    - wsl
    - lll
    - dupl
    - funlen
    - gochecknoinits
    - gochecknoglobals
    - godox
    - maligned
    - gocognit
    - gocyclo
    - interfacer
    - gomnd
    - goerr113
    - nlreturn
    - ifshort
    - golint
    - scopelint
    - cyclop
  fast: false
